font:
  normal:
    family: hack 
    style: Regular
    size: 9.0

  bold:
    family: hack 
    style: Regular 
    size: 9.0

  italic:
    family: hack 
    style: Italic

background_opacity: 0.8
size: 9.0
