theme = "onedark"

[editor]
line-number = "absolute"
mouse = false
gutters = ["diff", "line-numbers", "spacer"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[keys.insert.j]
k = "normal_mode"

[keys.normal]
"tab" = "page_up"
"ret" = "page_down"



